import "dotenv/config";
import { PrismaClient } from "./generated/client";
import { PrismaPg } from "@prisma/adapter-pg";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

const IMAGE_BASE = "https://picsum.photos/seed";

function img(seed: string): string {
  return `${IMAGE_BASE}/${seed}/640/480`;
}

async function main() {
  console.log("Seeding ELOHOME database...");

  const STATIONERY = "STATIONERY" as const;
  const ELECTRONICS = "ELECTRONICS" as const;
  const SOFTWARE = "SOFTWARE" as const;

  const products = [
    // ─── PRINTERS ───────────────────────────────────────────────
    {
      name: "Touch Screen POS Terminal P70E (Double Screen)",
      slug: "touch-screen-pos-p70e-double",
      description: "Professional double-screen POS terminal with integrated barcode scanning. Perfect for retail stores, supermarkets, and restaurants. Features a customer-facing display and high-speed transaction processing.",
      category: ELECTRONICS,
      brand: "P70E",
      sku: "POS-P70E-DS",
      retailPrice: 600000,
      bulkPrice: 550000,
      bulkMinQty: 5,
      stockStatus: "IN_STOCK",
      featured: true,
      image: img("pos-p70e-ds"),
      imageAlt: "Touch Screen POS Terminal Double Screen P70E",
    },
    {
      name: "Touch Screen POS Terminal P70E (Single Screen)",
      slug: "touch-screen-pos-p70e-single",
      description: "Single-screen POS terminal with barcode scanner. Compact and efficient for small to medium businesses. Easy to set up and use.",
      category: ELECTRONICS,
      brand: "P70E",
      sku: "POS-P70E-SS",
      retailPrice: 500000,
      bulkPrice: 460000,
      bulkMinQty: 5,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("pos-p70e-ss"),
      imageAlt: "Touch Screen POS Terminal Single Screen P70E",
    },
    {
      name: "Xprinter XP-245B Thermal Printer",
      slug: "xprinter-xp-245b",
      description: "High-speed thermal receipt printer for POS systems. Reliable and durable for high-volume printing in retail and hospitality environments.",
      category: ELECTRONICS,
      brand: "Xprinter",
      sku: "XPR-245B",
      retailPrice: 80000,
      bulkPrice: 72000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("xprinter-245b"),
      imageAlt: "Xprinter XP-245B Thermal Printer",
    },
    {
      name: "Xprinter XP-365B Thermal Printer",
      slug: "xprinter-xp-365b",
      description: "Advanced thermal receipt printer with faster printing speed and greater durability. Ideal for busy retail environments.",
      category: ELECTRONICS,
      brand: "Xprinter",
      sku: "XPR-365B",
      retailPrice: 130000,
      bulkPrice: 118000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: true,
      image: img("xprinter-365b"),
      imageAlt: "Xprinter XP-365B Thermal Printer",
    },
    {
      name: "Xprinter XP-58TS Mini Thermal Printer 58mm USB",
      slug: "xprinter-xp-58ts-usb",
      description: "Compact mini thermal printer with USB connectivity. 58mm paper width, perfect for small receipts and ticket printing.",
      category: ELECTRONICS,
      brand: "Xprinter",
      sku: "XPR-58TS",
      retailPrice: 35000,
      bulkPrice: 30000,
      bulkMinQty: 20,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("xprinter-58ts"),
      imageAlt: "Xprinter Mini Thermal Printer XP-58TS",
    },
    {
      name: "Xprinter XP-59TS Mini Thermal Printer USB+Bluetooth",
      slug: "xprinter-xp-59ts-bt",
      description: "Wireless mini thermal printer with USB and Bluetooth connectivity. 58mm paper, perfect for mobile POS setups.",
      category: ELECTRONICS,
      brand: "Xprinter",
      sku: "XPR-59TS",
      retailPrice: 45000,
      bulkPrice: 40000,
      bulkMinQty: 20,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("xprinter-59ts"),
      imageAlt: "Xprinter Mini Thermal Printer XP-59TS Bluetooth",
    },
    {
      name: "Mobile Thermal Printer 58mm",
      slug: "mobile-thermal-printer-58mm",
      description: "Portable mobile thermal printer for on-the-go printing. Ideal for delivery services, field operations, and mobile businesses.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "MTP-58MM",
      retailPrice: 45000,
      bulkPrice: 40000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("mobile-thermal-58"),
      imageAlt: "Mobile Thermal Printer 58mm",
    },
    {
      name: "Handheld Android Terminal",
      slug: "handheld-android-terminal",
      description: "Powerful handheld Android terminal for inventory management, order processing, and field data collection. Runs Android OS with barcode scanning capabilities.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "HAT-ANDROID",
      retailPrice: 190000,
      bulkPrice: 175000,
      bulkMinQty: 5,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("android-terminal"),
      imageAlt: "Handheld Android Terminal",
    },
    {
      name: "Konica Minolta Printer",
      slug: "konica-minolta-printer",
      description: "Professional-grade Konica Minolta printer for high-volume office printing. Delivers exceptional print quality and reliability.",
      category: ELECTRONICS,
      brand: "Konica Minolta",
      sku: "KON-MP",
      retailPrice: 4000000,
      bulkPrice: 3800000,
      bulkMinQty: 2,
      stockStatus: "IN_STOCK",
      featured: true,
      image: img("konica-printer"),
      imageAlt: "Konica Minolta Printer",
    },
    {
      name: "Epson L8058 Printer",
      slug: "epson-l8058",
      description: "High-quality Epson L8058 inkjet printer with exceptional print speed and color accuracy. Ideal for professional photo printing and office use.",
      category: ELECTRONICS,
      brand: "Epson",
      sku: "EPS-L8058",
      retailPrice: 550000,
      bulkPrice: 500000,
      bulkMinQty: 5,
      stockStatus: "IN_STOCK",
      featured: true,
      image: img("epson-l8058"),
      imageAlt: "Epson L8058 Printer",
    },
    {
      name: "Epson L3258 Printer",
      slug: "epson-l3258",
      description: "Affordable Epson L3258 multifunction printer. Print, scan, and copy with ease. Perfect for home and small office use.",
      category: ELECTRONICS,
      brand: "Epson",
      sku: "EPS-L3258",
      retailPrice: 260000,
      bulkPrice: 240000,
      bulkMinQty: 5,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("epson-l3258"),
      imageAlt: "Epson L3258 Printer",
    },
    {
      name: "Xprinter XP-80T Thermal Printer 80mm",
      slug: "xprinter-xp-80t",
      description: "80mm thermal receipt printer for professional POS systems. High-speed printing with reliable performance.",
      category: ELECTRONICS,
      brand: "Xprinter",
      sku: "XPR-80T",
      retailPrice: 80000,
      bulkPrice: 72000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("xprinter-80t"),
      imageAlt: "Xprinter XP-80T Thermal Printer 80mm",
    },
    {
      name: "Epson L805 Printer",
      slug: "epson-l805",
      description: "Epson L805 inkjet printer with excellent photo printing capabilities. Wide color gamut and high-resolution output.",
      category: ELECTRONICS,
      brand: "Epson",
      sku: "EPS-L805",
      retailPrice: 550000,
      bulkPrice: 500000,
      bulkMinQty: 5,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("epson-l805"),
      imageAlt: "Epson L805 Printer",
    },

    // ─── PRINTER PAPER ──────────────────────────────────────────
    {
      name: "Thermal Paper Roll 80x80mm",
      slug: "thermal-paper-80x80",
      description: "High-quality thermal paper roll for receipt printers. 80mm width x 80mm diameter. Compatible with most thermal receipt printers.",
      category: STATIONERY,
      brand: "Generic",
      sku: "TP-8080",
      retailPrice: 80000,
      bulkPrice: 70000,
      bulkMinQty: 50,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("thermal-paper-80"),
      imageAlt: "Thermal Paper Roll 80x80mm",
    },
    {
      name: "Thermal Barcode Paper 40x30x800",
      slug: "thermal-barcode-paper-40x30",
      description: "Thermal barcode label paper, 40mm x 30mm x 800 labels per roll. Perfect for product labeling and inventory management.",
      category: STATIONERY,
      brand: "Generic",
      sku: "TBP-4030",
      retailPrice: 150000,
      bulkPrice: 135000,
      bulkMinQty: 20,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("barcode-paper-40"),
      imageAlt: "Thermal Barcode Paper 40x30mm",
    },
    {
      name: "Thermal Barcode Paper 60x40x800",
      slug: "thermal-barcode-paper-60x40",
      description: "Large thermal barcode label paper, 60mm x 40mm x 800 labels per roll. Ideal for shipping labels and product identification.",
      category: STATIONERY,
      brand: "Generic",
      sku: "TBP-6040",
      retailPrice: 250000,
      bulkPrice: 225000,
      bulkMinQty: 20,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("barcode-paper-60"),
      imageAlt: "Thermal Barcode Paper 60x40mm",
    },
    {
      name: "Xprinter Paper 57mm",
      slug: "xprinter-paper-57mm",
      description: "Thermal paper rolls for Xprinter and compatible mini printers. 57mm width, standard roll size.",
      category: STATIONERY,
      brand: "Xprinter",
      sku: "XPR-P57",
      retailPrice: 40000,
      bulkPrice: 35000,
      bulkMinQty: 50,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("xprinter-paper-57"),
      imageAlt: "Xprinter Paper 57mm",
    },

    // ─── VIDEOGRAPHY TOOLS ──────────────────────────────────────
    {
      name: "LED Photographic Lamp 40W",
      slug: "led-photographic-lamp-40w",
      description: "Professional 40W LED photographic lamp for studio photography and videography. High brightness with adjustable color temperature.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "LED-40W-PL",
      retailPrice: 60000,
      bulkPrice: 55000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("led-lamp-40w"),
      imageAlt: "LED Photographic Lamp 40W",
    },
    {
      name: "Soulmate NI-MH Charger Set",
      slug: "soulmate-nimh-charger",
      description: "NI-MH battery charger set for rechargeable batteries. Ideal for photographers and videographers who need reliable power.",
      category: ELECTRONICS,
      brand: "Soulmate",
      sku: "SLM-NIMH",
      retailPrice: 35000,
      bulkPrice: 32000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("soulmate-charger"),
      imageAlt: "Soulmate NI-MH Charger Set",
    },
    {
      name: "WL-98 Tricolor LED Video Light",
      slug: "wl-98-tricolor-led",
      description: "WL-98 tricolor LED video light with adjustable color temperature and brightness. Perfect for video recording and live streaming.",
      category: ELECTRONICS,
      brand: "WL",
      sku: "WL-98",
      retailPrice: 30000,
      bulkPrice: 27000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("wl98-video-light"),
      imageAlt: "WL-98 Tricolor LED Video Light",
    },
    {
      name: "M-66 Pro LED Video Light",
      slug: "m-66-pro-led",
      description: "Professional M-66 Pro LED video light with high CRI rating. Ideal for professional video production and photography.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "M66-PRO",
      retailPrice: 45000,
      bulkPrice: 40000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("m66-pro-light"),
      imageAlt: "M-66 Pro LED Video Light",
    },
    {
      name: "8806 Light Stand Tripod",
      slug: "8806-light-stand-tripod",
      description: "Professional light stand tripod for studio lighting. Adjustable height, stable base, and durable construction.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "LS-8806",
      retailPrice: 25000,
      bulkPrice: 22000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("light-stand-8806"),
      imageAlt: "8806 Light Stand Tripod",
    },
    {
      name: "Varicorm Pro LED 800 Video Light Kit",
      slug: "varicorm-pro-led-800",
      description: "Professional photo and video LED light kit with Varicorm Pro LED 800. Comprehensive lighting solution for studios.",
      category: ELECTRONICS,
      brand: "Varicorm",
      sku: "VPL-800",
      retailPrice: 60000,
      bulkPrice: 55000,
      bulkMinQty: 5,
      stockStatus: "IN_STOCK",
      featured: true,
      image: img("varicorm-800"),
      imageAlt: "Varicorm Pro LED 800 Light Kit",
    },
    {
      name: "Caricorm Pro LED 600 Video Light Kit",
      slug: "caricorm-pro-led-600",
      description: "Professional photo and video LED light kit with Caricorm Pro LED 600. Perfect for content creators and small studios.",
      category: ELECTRONICS,
      brand: "Caricorm",
      sku: "CPL-600",
      retailPrice: 50000,
      bulkPrice: 45000,
      bulkMinQty: 5,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("caricorm-600"),
      imageAlt: "Caricorm Pro LED 600 Light Kit",
    },
    {
      name: "3-Axis Smartphone Stabilizer Smart X2",
      slug: "smartphone-stabilizer-smart-x2",
      description: "Professional 3-axis smartphone stabilizer for smooth video recording. Compatible with most smartphones. Features intuitive controls and long battery life.",
      category: ELECTRONICS,
      brand: "Smart",
      sku: "SS-SX2",
      retailPrice: 150000,
      bulkPrice: 135000,
      bulkMinQty: 5,
      stockStatus: "IN_STOCK",
      featured: true,
      image: img("stabilizer-x2"),
      imageAlt: "3-Axis Smartphone Stabilizer Smart X2",
    },
    {
      name: "3-Axis Smartphone Stabilizer Smart XE",
      slug: "smartphone-stabilizer-smart-xe",
      description: "Compact 3-axis smartphone stabilizer for smooth video. Lightweight and portable with advanced stabilization technology.",
      category: ELECTRONICS,
      brand: "Smart",
      sku: "SS-SXE",
      retailPrice: 120000,
      bulkPrice: 108000,
      bulkMinQty: 5,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("stabilizer-xe"),
      imageAlt: "3-Axis Smartphone Stabilizer Smart XE",
    },
    {
      name: "Phone Camera Tripod",
      slug: "phone-camera-tripod",
      description: "Compact tripod for phone photography and videography. Adjustable height with universal phone holder.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "PCT-BASIC",
      retailPrice: 10000,
      bulkPrice: 8500,
      bulkMinQty: 20,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("phone-tripod"),
      imageAlt: "Phone Camera Tripod",
    },
    {
      name: "Selfie Stick Quadrupod C12 1.8M",
      slug: "selfie-stick-quadrupod-c12",
      description: "Stable selfie stick with Quadrupod legs. Extends to 1.8 meters. Perfect for group photos, vlogging, and content creation.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "SS-C12",
      retailPrice: 60000,
      bulkPrice: 54000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("quadrupod-c12"),
      imageAlt: "Selfie Stick Quadrupod C12 1.8M",
    },
    {
      name: "360 Auto Face Tracking Selfie Stick Tripod Q02",
      slug: "auto-face-tracking-selfie-stick-q02",
      description: "Smart selfie stick with 360-degree auto face tracking. Built-in tripod stand for hands-free recording.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "AFT-Q02",
      retailPrice: 70000,
      bulkPrice: 63000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: true,
      image: img("face-track-q02"),
      imageAlt: "360 Auto Face Tracking Selfie Stick Q02",
    },

    // ─── SECURITY CAMERAS ──────────────────────────────────────
    {
      name: "FOSVision 8MP Solar Camera 4 Lens",
      slug: "fosvision-8mp-solar-4lens",
      description: "Advanced solar-powered security camera with 8MP resolution and 4 lenses for comprehensive 360-degree surveillance. Perfect for outdoor security.",
      category: ELECTRONICS,
      brand: "FOSVision",
      sku: "FOS-SOLAR-8MP-4L",
      retailPrice: 200000,
      bulkPrice: 180000,
      bulkMinQty: 5,
      stockStatus: "IN_STOCK",
      featured: true,
      image: img("fosvision-solar"),
      imageAlt: "FOSVision 8MP Solar Camera 4 Lens",
    },
    {
      name: "FOSVision 8MP Ultra Wireless Camera 4 Lens",
      slug: "fosvision-8mp-ultra-wireless-4lens",
      description: "Ultra HD wireless security camera with 8MP resolution and 4 adjustable lenses. Night vision and motion detection included.",
      category: ELECTRONICS,
      brand: "FOSVision",
      sku: "FOS-UW-8MP-4L",
      retailPrice: 120000,
      bulkPrice: 108000,
      bulkMinQty: 5,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("fosvision-wireless"),
      imageAlt: "FOSVision 8MP Ultra Wireless Camera",
    },
    {
      name: "Dual Lens Smart Outdoor Camera 2 Lens",
      slug: "dual-lens-smart-outdoor-camera",
      description: "Smart outdoor security camera with dual lenses for wide-angle coverage. Motion detection, night vision, and smartphone alerts.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "DL-SOC-2L",
      retailPrice: 80000,
      bulkPrice: 72000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("dual-lens-camera"),
      imageAlt: "Dual Lens Smart Outdoor Camera",
    },
    {
      name: "FOSVision 4K HD Smart AI Camera 3 Lens",
      slug: "fosvision-4k-ai-3lens",
      description: "Smart AI security camera with 4K HD resolution and 3 lenses. AI-powered detection with human and vehicle recognition.",
      category: ELECTRONICS,
      brand: "FOSVision",
      sku: "FOS-AI-4K-3L",
      retailPrice: 85000,
      bulkPrice: 76000,
      bulkMinQty: 5,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("fosvision-ai"),
      imageAlt: "FOSVision 4K HD Smart AI Camera",
    },
    {
      name: "FOSVision Mini WiFi Camera",
      slug: "fosvision-mini-wifi",
      description: "Compact mini WiFi camera for indoor surveillance. Small footprint with full HD recording and remote viewing via smartphone app.",
      category: ELECTRONICS,
      brand: "FOSVision",
      sku: "FOS-MINI-WIFI",
      retailPrice: 50000,
      bulkPrice: 45000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("fosvision-mini"),
      imageAlt: "FOSVision Mini WiFi Camera",
    },
    {
      name: "Smart Security Camera",
      slug: "smart-security-camera",
      description: "Versatile smart security camera with night vision, two-way audio, and motion detection. Compatible with smartphone app for remote monitoring.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "SSC-BASIC",
      retailPrice: 45000,
      bulkPrice: 40000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("smart-cam"),
      imageAlt: "Smart Security Camera",
    },

    // ─── WEBCAMS ────────────────────────────────────────────────
    {
      name: "Full HD 1080P Web Camera",
      slug: "full-hd-1080p-webcam",
      description: "High-definition webcam with 1080P resolution. Plug-and-play USB connectivity. Perfect for video calls, conferencing, and streaming.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "WBC-1080P",
      retailPrice: 20000,
      bulkPrice: 17000,
      bulkMinQty: 20,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("webcam-1080p"),
      imageAlt: "Full HD 1080P Web Camera",
    },
    {
      name: "Logitech C270 HD Webcam",
      slug: "logitech-c270-hd",
      description: "Trusted Logitech C270 HD webcam with 720P video and built-in microphone. Reliable performance for everyday video calls.",
      category: ELECTRONICS,
      brand: "Logitech",
      sku: "LOG-C270",
      retailPrice: 60000,
      bulkPrice: 54000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("logitech-c270"),
      imageAlt: "Logitech C270 HD Webcam",
    },

    // ─── KIDS CAMERAS ────────────────────────────────────────────
    {
      name: "FujiFilm Instax Mini SE",
      slug: "fujifilm-instax-mini-se",
      description: "FujiFilm Instax Mini SE instant camera. Create credit-card sized photos instantly. Fun and easy to use for all ages.",
      category: ELECTRONICS,
      brand: "FujiFilm",
      sku: "FUJI-INSTAX-SE",
      retailPrice: 250000,
      bulkPrice: 230000,
      bulkMinQty: 5,
      stockStatus: "IN_STOCK",
      featured: true,
      image: img("instax-se"),
      imageAlt: "FujiFilm Instax Mini SE Camera",
    },
    {
      name: "FujiFilm Instax Mini Film 10 Sheets",
      slug: "fujifilm-instax-film-10sheets",
      description: "Official FujiFilm Instax Mini instant film. 10 sheets per pack. Compatible with all Instax Mini cameras.",
      category: STATIONERY,
      brand: "FujiFilm",
      sku: "FUJI-INSTAX-F10",
      retailPrice: 25000,
      bulkPrice: 22000,
      bulkMinQty: 20,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("instax-film"),
      imageAlt: "FujiFilm Instax Mini Film 10 Sheets",
    },
    {
      name: "DIY Instant Digital Camera Print I-365",
      slug: "diy-instant-digital-camera-i365",
      description: "DIY instant digital camera that prints photos instantly. Fun creative project for kids and adults. Includes printing functionality.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "DIC-I365",
      retailPrice: 50000,
      bulkPrice: 45000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("diy-camera-i365"),
      imageAlt: "DIY Instant Digital Camera Print I-365",
    },

    // ─── GAMING GADGETS ─────────────────────────────────────────
    {
      name: "PlayStation PS4 Controller",
      slug: "playstation-ps4-controller",
      description: "Official Sony PlayStation 4 wireless controller. Ergonomic design with precise controls and built-in speaker.",
      category: ELECTRONICS,
      brand: "Sony",
      sku: "SONY-PS4-CTRL",
      retailPrice: 25000,
      bulkPrice: 22000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("ps4-controller"),
      imageAlt: "PlayStation PS4 Controller",
    },
    {
      name: "Smart Controller Wireless Gamepad HJ-850",
      slug: "wireless-gamepad-hj-850",
      description: "Wireless game controller with ergonomic design. Compatible with PC, Android TV, and gaming consoles.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "GP-HJ850",
      retailPrice: 20000,
      bulkPrice: 18000,
      bulkMinQty: 20,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("gamepad-hj850"),
      imageAlt: "Wireless Gamepad HJ-850",
    },
    {
      name: "PlayStation PS5 Controller",
      slug: "playstation-ps5-controller",
      description: "Official Sony PlayStation 5 DualSense wireless controller with haptic feedback, adaptive triggers, and built-in microphone.",
      category: ELECTRONICS,
      brand: "Sony",
      sku: "SONY-PS5-CTRL",
      retailPrice: 110000,
      bulkPrice: 100000,
      bulkMinQty: 5,
      stockStatus: "IN_STOCK",
      featured: true,
      image: img("ps5-controller"),
      imageAlt: "PlayStation PS5 DualSense Controller",
    },
    {
      name: "2.4G Wireless Game Stick MP5 TV Games",
      slug: "wireless-game-stick-mp5",
      description: "2.4G wireless game stick with built-in MP5 TV games. Plug and play on any TV. Includes thousands of classic games.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "GS-MP5",
      retailPrice: 50000,
      bulkPrice: 45000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("game-stick-mp5"),
      imageAlt: "2.4G Wireless Game Stick MP5",
    },
    {
      name: "Milang Gaming Keyboard",
      slug: "milang-gaming-keyboard",
      description: "RGB backlit gaming keyboard by Milang. Mechanical feel keys with multimedia controls. Perfect for gaming and productivity.",
      category: ELECTRONICS,
      brand: "Milang",
      sku: "MLG-KEY",
      retailPrice: 15000,
      bulkPrice: 13000,
      bulkMinQty: 20,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("milang-keyboard"),
      imageAlt: "Milang Gaming Keyboard",
    },
    {
      name: "Game Projector 2-in-1 Professional Chip",
      slug: "game-projector-2in1",
      description: "2-in-1 game projector with professional chip. Projects games and media on any surface. Built-in speakers and HD support.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "GP-2IN1",
      retailPrice: 105000,
      bulkPrice: 95000,
      bulkMinQty: 5,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("game-projector"),
      imageAlt: "Game Projector 2-in-1",
    },
    {
      name: "Fighter X6S Micro Pro Mouse",
      slug: "fighter-x6s-micro-pro-mouse",
      description: "High-precision gaming mouse with adjustable DPI and RGB lighting. Ergonomic design for extended gaming sessions.",
      category: ELECTRONICS,
      brand: "Biagji",
      sku: "FG-X6S",
      retailPrice: 10000,
      bulkPrice: 8500,
      bulkMinQty: 20,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("fighter-x6s"),
      imageAlt: "Fighter X6S Micro Pro Mouse",
    },

    // ─── FANS & AIR COOLING ────────────────────────────────────
    {
      name: "Gadery 4-in-1 Rechargeable LED Fan 607",
      slug: "gadery-4in1-led-fan-607",
      description: "Multi-functional rechargeable fan with LED lamp. 4-in-1 design: fan, light, power bank, and aroma diffuser. Model 607.",
      category: ELECTRONICS,
      brand: "Gadery",
      sku: "GAD-607",
      retailPrice: 70000,
      bulkPrice: 63000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: true,
      image: img("gadery-607"),
      imageAlt: "Gadery 4-in-1 Rechargeable LED Fan 607",
    },
    {
      name: "Gadery 4-in-1 Rechargeable LED Fan 606",
      slug: "gadery-4in1-led-fan-606",
      description: "Rechargeable fan with LED lighting. 4-in-1 functionality. Compact design perfect for home and office. Model 606.",
      category: ELECTRONICS,
      brand: "Gadery",
      sku: "GAD-606",
      retailPrice: 60000,
      bulkPrice: 54000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("gadery-606"),
      imageAlt: "Gadery 4-in-1 Rechargeable LED Fan 606",
    },
    {
      name: "Gadery Air Color Fan G-168",
      slug: "gadery-air-color-fan-g168",
      description: "Stylish air color fan with multiple speed settings. Quiet operation with oscillating function. Model G-168.",
      category: ELECTRONICS,
      brand: "Gadery",
      sku: "GAD-G168",
      retailPrice: 140000,
      bulkPrice: 126000,
      bulkMinQty: 5,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("gadery-g168"),
      imageAlt: "Gadery Air Color Fan G-168",
    },
    {
      name: "Gadery Cold & Warm Air Conditioning Fan G-032/033",
      slug: "gadery-ac-fan-g032-033",
      description: "Dual-function air conditioning fan with cold and warm settings. Cools and heats your space efficiently. Models G-032/G-033.",
      category: ELECTRONICS,
      brand: "Gadery",
      sku: "GAD-G032",
      retailPrice: 150000,
      bulkPrice: 135000,
      bulkMinQty: 5,
      stockStatus: "IN_STOCK",
      featured: true,
      image: img("gadery-g032"),
      imageAlt: "Gadery Cold and Warm Air Conditioning Fan",
    },
    {
      name: "Gadery Fan GF09",
      slug: "gadery-fan-gf09",
      description: "Compact and powerful desk fan by Gadery. Quiet operation with adjustable tilt. Perfect for personal cooling.",
      category: ELECTRONICS,
      brand: "Gadery",
      sku: "GAD-GF09",
      retailPrice: 45000,
      bulkPrice: 40000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("gadery-gf09"),
      imageAlt: "Gadery Fan GF09",
    },
    {
      name: "Gadery USB Desktop Circulation Fan GF82",
      slug: "gadery-usb-circulation-fan-gf82",
      description: "USB-powered desktop circulation fan. Energy-efficient with quiet operation. Perfect for desk use at home or office.",
      category: ELECTRONICS,
      brand: "Gadery",
      sku: "GAD-GF82",
      retailPrice: 50000,
      bulkPrice: 45000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("gadery-gf82"),
      imageAlt: "Gadery USB Desktop Circulation Fan GF82",
    },
    {
      name: "Gadery Air Circulation Fan",
      slug: "gadery-air-circulation-fan",
      description: "Powerful air circulation fan for room ventilation. Promotes airflow and comfort in any space.",
      category: ELECTRONICS,
      brand: "Gadery",
      sku: "GAD-ACF",
      retailPrice: 95000,
      bulkPrice: 85000,
      bulkMinQty: 5,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("gadery-circulation"),
      imageAlt: "Gadery Air Circulation Fan",
    },
    {
      name: "Gadery 6-in-1 Rechargeable LED Fan N283",
      slug: "gadery-6in1-led-fan-n283",
      description: "Multi-functional 6-in-1 rechargeable fan with LED lamp, power bank, Bluetooth speaker, and more. Model N283.",
      category: ELECTRONICS,
      brand: "Gadery",
      sku: "GAD-N283",
      retailPrice: 95000,
      bulkPrice: 85000,
      bulkMinQty: 5,
      stockStatus: "IN_STOCK",
      featured: true,
      image: img("gadery-n283"),
      imageAlt: "Gadery 6-in-1 Rechargeable LED Fan N283",
    },
    {
      name: "Handheld Rechargeable Fan",
      slug: "handheld-rechargeable-fan",
      description: "Portable handheld rechargeable fan. Perfect for travel, outdoor activities, and personal cooling on the go.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "HH-FAN",
      retailPrice: 25000,
      bulkPrice: 22000,
      bulkMinQty: 20,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("handheld-fan"),
      imageAlt: "Handheld Rechargeable Fan",
    },

    // ─── HEADPHONES & HEADSETS ─────────────────────────────────
    {
      name: "AirPods Max with Smart Case",
      slug: "airpods-max-smart-case",
      description: "Premium over-ear headphones with active noise cancellation and Smart Case. Exceptional audio quality from Apple.",
      category: ELECTRONICS,
      brand: "Apple",
      sku: "APL-AIRPODS-MAX",
      retailPrice: 30000,
      bulkPrice: 27000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: true,
      image: img("airpods-max"),
      imageAlt: "AirPods Max with Smart Case",
    },
    {
      name: "AirPods Max Original with Smart Case",
      slug: "airpods-max-original",
      description: "Genuine Apple AirPods Max with original Smart Case. Premium build quality, spatial audio, and seamless Apple ecosystem integration.",
      category: ELECTRONICS,
      brand: "Apple",
      sku: "APL-AIRPODS-MAX-OG",
      retailPrice: 190000,
      bulkPrice: 175000,
      bulkMinQty: 5,
      stockStatus: "IN_STOCK",
      featured: true,
      image: img("airpods-max-og"),
      imageAlt: "AirPods Max Original with Smart Case",
    },
    {
      name: "JBL by Harman Headphones",
      slug: "jbl-harman-headphones",
      description: "JBL headphones engineered by Harman. Rich bass and crystal-clear audio. Comfortable fit for extended listening.",
      category: ELECTRONICS,
      brand: "JBL",
      sku: "JBL-HARMAN",
      retailPrice: 30000,
      bulkPrice: 27000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("jbl-headphones"),
      imageAlt: "JBL by Harman Headphones",
    },
    {
      name: "Bose Headphones",
      slug: "bose-headphones",
      description: "Bose over-ear headphones with world-class noise cancellation. Superior comfort and immersive sound quality.",
      category: ELECTRONICS,
      brand: "Bose",
      sku: "BOSE-HEAD",
      retailPrice: 30000,
      bulkPrice: 27000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("bose-headphones"),
      imageAlt: "Bose Headphones",
    },
    {
      name: "Sony Wireless Headset",
      slug: "sony-wireless-headset",
      description: "Sony wireless headset with noise cancellation and high-resolution audio. Premium build and exceptional battery life.",
      category: ELECTRONICS,
      brand: "Sony",
      sku: "SONY-HEADSET",
      retailPrice: 35000,
      bulkPrice: 32000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("sony-headset"),
      imageAlt: "Sony Wireless Headset",
    },
    {
      name: "Marshall Major IV Headphones",
      slug: "marshall-major-iv",
      description: "Iconic Marshall Major IV headphones with signature sound. Foldable design with 80+ hours of wireless playtime.",
      category: ELECTRONICS,
      brand: "Marshall",
      sku: "MAR-MAJOR-IV",
      retailPrice: 30000,
      bulkPrice: 27000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("marshall-major-iv"),
      imageAlt: "Marshall Major IV Headphones",
    },
    {
      name: "AirPods Pro",
      slug: "airpods-pro",
      description: "Apple AirPods Pro with active noise cancellation, transparency mode, and customizable fit. Spatial audio for immersive listening.",
      category: ELECTRONICS,
      brand: "Apple",
      sku: "APL-AIRPODS-PRO",
      retailPrice: 50000,
      bulkPrice: 45000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("airpods-pro"),
      imageAlt: "AirPods Pro",
    },
    {
      name: "AirPods Pro Original",
      slug: "airpods-pro-original",
      description: "Genuine Apple AirPods Pro. Original quality with all features including ANC, transparency, and spatial audio.",
      category: ELECTRONICS,
      brand: "Apple",
      sku: "APL-AIRPODS-PRO-OG",
      retailPrice: 25000,
      bulkPrice: 22000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("airpods-pro-og"),
      imageAlt: "AirPods Pro Original",
    },

    // ─── BILL COUNTERS ──────────────────────────────────────────
    {
      name: "Duhan S500 Bill Counter",
      slug: "duhan-s500-bill-counter",
      description: "Professional bill counting machine by Duhan. High-speed counting with counterfeit detection. Ideal for banks and retail.",
      category: ELECTRONICS,
      brand: "Duhan",
      sku: "DUH-S500",
      retailPrice: 200000,
      bulkPrice: 180000,
      bulkMinQty: 5,
      stockStatus: "IN_STOCK",
      featured: true,
      image: img("duhan-s500"),
      imageAlt: "Duhan S500 Bill Counter",
    },
    {
      name: "Bill Counter M:2107 UV/MG",
      slug: "bill-counter-2107-uv-mg",
      description: "Bill counter with UV and MG counterfeit detection. Red color model. Accurate counting with dual detection modes.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "BC-2107",
      retailPrice: 150000,
      bulkPrice: 135000,
      bulkMinQty: 5,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("bill-counter-2107"),
      imageAlt: "Bill Counter M:2107 UV/MG",
    },
    {
      name: "Standard Bill Counter",
      slug: "standard-bill-counter",
      description: "Reliable bill counting machine for everyday use. Accurate counting with counterfeit detection features.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "BC-STD",
      retailPrice: 200000,
      bulkPrice: 180000,
      bulkMinQty: 5,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("bill-counter-std"),
      imageAlt: "Standard Bill Counter",
    },

    // ─── STANDS ──────────────────────────────────────────────────
    {
      name: "Folding Desktop Phone Stand",
      slug: "folding-desktop-phone-stand",
      description: "Compact folding phone stand for desk use. Universal fit for all smartphones. Lightweight and portable.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "STD-FOLD",
      retailPrice: 5000,
      bulkPrice: 4000,
      bulkMinQty: 50,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("phone-stand-fold"),
      imageAlt: "Folding Desktop Phone Stand",
    },
    {
      name: "Magnetic Phone Bracket K007",
      slug: "magnetic-phone-bracket-k007",
      description: "Magnetic phone bracket for hands-free use. Strong magnetic hold with 360-degree rotation. Model K007.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "MB-K007",
      retailPrice: 10000,
      bulkPrice: 8500,
      bulkMinQty: 20,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("magnetic-bracket-k007"),
      imageAlt: "Magnetic Phone Bracket K007",
    },
    {
      name: "Adjustable Laptop Stand",
      slug: "adjustable-laptop-stand",
      description: "Ergonomic adjustable laptop stand for improved posture and airflow. Foldable and portable design.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "LPS-ADJ",
      retailPrice: 35000,
      bulkPrice: 30000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("laptop-stand-adj"),
      imageAlt: "Adjustable Laptop Stand",
    },
    {
      name: "Laptop Stand with X360 Rotation Fan",
      slug: "laptop-stand-x360-fan",
      description: "Laptop stand with built-in 360-degree rotating fan. Keeps your laptop cool while providing ergonomic viewing angle.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "LPS-X360",
      retailPrice: 25000,
      bulkPrice: 22000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("laptop-stand-x360"),
      imageAlt: "Laptop Stand with X360 Fan",
    },
    {
      name: "Basic Laptop Stand",
      slug: "basic-laptop-stand",
      description: "Simple and sturdy laptop stand for desk use. Elevates your laptop for better ergonomics and cooling.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "LPS-BASIC",
      retailPrice: 15000,
      bulkPrice: 13000,
      bulkMinQty: 20,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("laptop-stand-basic"),
      imageAlt: "Basic Laptop Stand",
    },
    {
      name: "Wireless Charger Stand",
      slug: "wireless-charger-stand",
      description: "Wireless charging stand for smartphones. Fast charging compatible. Dual-angle viewing for video calls and media.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "WCS-STD",
      retailPrice: 30000,
      bulkPrice: 27000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("wireless-charger-stand"),
      imageAlt: "Wireless Charger Stand",
    },

    // ─── PROJECTORS ─────────────────────────────────────────────
    {
      name: "Ambient Lighting Pan-Tilt Projector",
      slug: "ambient-lighting-pan-tilt-projector",
      description: "Premium ambient lighting projector with pan and tilt control. Creates stunning visual ambiance for any room.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "PROJ-AMBIENT",
      retailPrice: 350000,
      bulkPrice: 320000,
      bulkMinQty: 3,
      stockStatus: "IN_STOCK",
      featured: true,
      image: img("ambient-projector"),
      imageAlt: "Ambient Lighting Pan-Tilt Projector",
    },
    {
      name: "A10 LCD Full HD Video Projector",
      slug: "a10-lcd-full-hd-projector",
      description: "A10 LCD projector with Full HD resolution. Perfect for home theater, presentations, and gaming. Built-in speakers.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "PROJ-A10",
      retailPrice: 170000,
      bulkPrice: 153000,
      bulkMinQty: 5,
      stockStatus: "IN_STOCK",
      featured: true,
      image: img("a10-projector"),
      imageAlt: "A10 LCD Full HD Video Projector",
    },

    // ─── MOUSE & KEYBOARD ACCESSORIES ──────────────────────────
    {
      name: "Multi-Device Mouse & Keyboard Kit",
      slug: "multi-device-mouse-keyboard-kit",
      description: "Wireless mouse and keyboard kit for multi-device connectivity. Switch between devices with one click.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "MKK-MULTI",
      retailPrice: 18000,
      bulkPrice: 16000,
      bulkMinQty: 20,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("mouse-kb-kit"),
      imageAlt: "Multi-Device Mouse & Keyboard Kit",
    },
    {
      name: "Wireless Bluetooth Dual Mode Keyboard & Mouse",
      slug: "wireless-bt-dual-mode-kb-mouse",
      description: "Dual mode wireless keyboard and mouse set with Bluetooth connectivity. Punching design with colorful backlight.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "BT-DM-KM",
      retailPrice: 35000,
      bulkPrice: 30000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("bt-dual-kb-mouse"),
      imageAlt: "Wireless Bluetooth Dual Mode Keyboard & Mouse",
    },
    {
      name: "Colorful Wireless Mouse & Keyboard Set",
      slug: "colorful-wireless-mouse-keyboard",
      description: "Vibrant wireless mouse and keyboard set. Colorful design with reliable wireless connectivity.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "CW-MK-SET",
      retailPrice: 30000,
      bulkPrice: 27000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("colorful-wireless-set"),
      imageAlt: "Colorful Wireless Mouse & Keyboard Set",
    },
    {
      name: "Keyboard Sticker Set",
      slug: "keyboard-sticker-set",
      description: "Protective keyboard sticker set. Keeps keys clean and visible. Easy to apply and remove.",
      category: STATIONERY,
      brand: "Generic",
      sku: "KBD-STICKER",
      retailPrice: 2000,
      bulkPrice: 1500,
      bulkMinQty: 100,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("keyboard-sticker"),
      imageAlt: "Keyboard Sticker Set",
    },
    {
      name: "Logitech Basic Mouse",
      slug: "logitech-basic-mouse",
      description: "Reliable Logitech wired mouse for everyday computing. Comfortable design with precise tracking.",
      category: ELECTRONICS,
      brand: "Logitech",
      sku: "LOG-M-BASIC",
      retailPrice: 6000,
      bulkPrice: 5000,
      bulkMinQty: 30,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("logitech-mouse-basic"),
      imageAlt: "Logitech Basic Mouse",
    },
    {
      name: "Logitech Premium Mouse",
      slug: "logitech-premium-mouse",
      description: "Premium Logitech mouse with advanced features. Ergonomic design with customizable buttons.",
      category: ELECTRONICS,
      brand: "Logitech",
      sku: "LOG-M-PREMIUM",
      retailPrice: 10000,
      bulkPrice: 8500,
      bulkMinQty: 20,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("logitech-mouse-premium"),
      imageAlt: "Logitech Premium Mouse",
    },

    // ─── CABLES & CHARGERS ──────────────────────────────────────
    {
      name: "External HDD Case USB 2.0",
      slug: "external-hdd-case-usb2",
      description: "External hard drive enclosure with USB 2.0 connectivity. Supports 2.5-inch SATA drives.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "HDC-USB2",
      retailPrice: 5000,
      bulkPrice: 4500,
      bulkMinQty: 30,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("hdd-case-usb2"),
      imageAlt: "External HDD Case USB 2.0",
    },
    {
      name: "External HDD Case USB 3.0",
      slug: "external-hdd-case-usb3",
      description: "External hard drive enclosure with high-speed USB 3.0 connectivity. Supports 2.5-inch SATA drives.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "HDC-USB3",
      retailPrice: 8000,
      bulkPrice: 7000,
      bulkMinQty: 30,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("hdd-case-usb3"),
      imageAlt: "External HDD Case USB 3.0",
    },
    {
      name: "M.2 NVMe Case",
      slug: "m2-nvme-case",
      description: "External enclosure for M.2 NVMe SSDs. High-speed data transfer with USB-C connectivity.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "M2C-NVME",
      retailPrice: 25000,
      bulkPrice: 22000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("m2-case"),
      imageAlt: "M.2 NVMe Case",
    },
    {
      name: "AI Smart Glasses",
      slug: "ai-smart-glasses",
      description: "Smart glasses with AI capabilities. Features camera, voice assistant, and augmented reality display.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "AI-GLASSES",
      retailPrice: 125000,
      bulkPrice: 112000,
      bulkMinQty: 5,
      stockStatus: "IN_STOCK",
      featured: true,
      image: img("ai-glasses"),
      imageAlt: "AI Smart Glasses",
    },
    {
      name: "Type-C to HDTV Dongle",
      slug: "type-c-to-hdtv-dongle",
      description: "USB Type-C to HDTV adapter dongle. Connect your device to TV or monitor for big-screen viewing.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "DNG-TC-HDTV",
      retailPrice: 20000,
      bulkPrice: 18000,
      bulkMinQty: 20,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("dongle-hdtv"),
      imageAlt: "Type-C to HDTV Dongle",
    },
    {
      name: "Type-C USB 3.0 Dongle",
      slug: "type-c-usb3-dongle",
      description: "USB Type-C to USB 3.0 adapter dongle. Expand your device connectivity with high-speed data transfer.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "DNG-TC-USB3",
      retailPrice: 15000,
      bulkPrice: 13000,
      bulkMinQty: 20,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("dongle-usb3"),
      imageAlt: "Type-C USB 3.0 Dongle",
    },
    {
      name: "Intelligent Film Cutter",
      slug: "intelligent-film-cutter",
      description: "Automatic intelligent film cutter for screen protectors. Cuts precise film sizes for any device.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "IFC-PRO",
      retailPrice: 600000,
      bulkPrice: 550000,
      bulkMinQty: 2,
      stockStatus: "IN_STOCK",
      featured: true,
      image: img("film-cutter"),
      imageAlt: "Intelligent Film Cutter",
    },
    {
      name: "Mini Massager",
      slug: "mini-massager",
      description: "Portable mini massager for muscle relief. Compact design with multiple speed settings.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "MSS-MINI",
      retailPrice: 30000,
      bulkPrice: 27000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("mini-massager"),
      imageAlt: "Mini Massager",
    },
    {
      name: "Massage Gun",
      slug: "massage-gun",
      description: "Deep tissue massage gun for muscle recovery. Multiple speed levels with interchangeable heads.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "MSS-GUN",
      retailPrice: 25000,
      bulkPrice: 22000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("massage-gun"),
      imageAlt: "Massage Gun",
    },
    {
      name: "Power Bank 10000mAh",
      slug: "power-bank-10000mah",
      description: "High-capacity 10000mAh power bank with fast charging. Dual USB output for charging multiple devices.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "PB-10000",
      retailPrice: 25000,
      bulkPrice: 22000,
      bulkMinQty: 20,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("power-bank"),
      imageAlt: "Power Bank 10000mAh",
    },
    {
      name: "Super Fast Charger Power Bank",
      slug: "super-fast-charger-power-bank",
      description: "Power bank with super fast charging technology. Quick charge compatible with USB-C Power Delivery.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "PB-FAST",
      retailPrice: 25000,
      bulkPrice: 22000,
      bulkMinQty: 20,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("fast-charger-pb"),
      imageAlt: "Super Fast Charger Power Bank",
    },
    {
      name: "iPhone USB Cable",
      slug: "iphone-usb-cable",
      description: "Durable iPhone charging and sync cable. MFi certified for reliable performance.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "CBL-IPHONE",
      retailPrice: 5000,
      bulkPrice: 4000,
      bulkMinQty: 50,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("iphone-cable"),
      imageAlt: "iPhone USB Cable",
    },
    {
      name: "iPhone Charger Adapter",
      slug: "iphone-charger-adapter",
      description: "iPhone wall charger adapter with fast charging support. Compact and travel-friendly design.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "CHG-IPHONE",
      retailPrice: 6000,
      bulkPrice: 5000,
      bulkMinQty: 30,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("iphone-charger"),
      imageAlt: "iPhone Charger Adapter",
    },
    {
      name: "USB-C to USB-C Cable",
      slug: "usb-c-to-usb-c-cable",
      description: "High-speed USB-C to USB-C charging and data cable. Supports fast charging and high-speed data transfer.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "CBL-USBC",
      retailPrice: 8000,
      bulkPrice: 7000,
      bulkMinQty: 30,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("usbc-cable"),
      imageAlt: "USB-C to USB-C Cable",
    },
    {
      name: "MacBook USB-C Power Adapter",
      slug: "macbook-usbc-power-adapter",
      description: "USB-C power adapter for MacBook. Fast charging compatible with multiple wattage options.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "ADP-MBP-USBC",
      retailPrice: 25000,
      bulkPrice: 22000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("macbook-adapter"),
      imageAlt: "MacBook USB-C Power Adapter",
    },
    {
      name: "85W MagSafe 2 Power Adapter MacBook",
      slug: "85w-magsafe-2-adapter",
      description: "85W MagSafe 2 power adapter for MacBook Pro. Genuine replacement with magnetic DC connector.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "ADP-MBP-MG2",
      retailPrice: 35000,
      bulkPrice: 30000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("magsafe2-85w"),
      imageAlt: "85W MagSafe 2 Power Adapter",
    },
    {
      name: "85W MagSafe Power Adapter MacBook",
      slug: "85w-magsafe-adapter",
      description: "85W MagSafe power adapter for MacBook Pro. Original replacement with T-shaped connector.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "ADP-MBP-MG1",
      retailPrice: 50000,
      bulkPrice: 45000,
      bulkMinQty: 5,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("magsafe-85w"),
      imageAlt: "85W MagSafe Power Adapter",
    },
    {
      name: "USB-C to MagSafe 3 Cable MacBook",
      slug: "usbc-to-magsafe-3-cable",
      description: "USB-C to MagSafe 3 charging cable for MacBook Pro. Fast charging with magnetic connector.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "CBL-MBP-MG3",
      retailPrice: 60000,
      bulkPrice: 54000,
      bulkMinQty: 5,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("magsafe3-cable"),
      imageAlt: "USB-C to MagSafe 3 Cable",
    },
    {
      name: "140W Laptop Charger Type-C to C",
      slug: "140w-laptop-charger-typec",
      description: "140W high-power laptop charger with USB-C to USB-C connectivity. Compatible with most modern laptops.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "CHG-140W",
      retailPrice: 75000,
      bulkPrice: 68000,
      bulkMinQty: 5,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("charger-140w"),
      imageAlt: "140W Laptop Charger Type-C",
    },
    {
      name: "Universal Laptop Adapter",
      slug: "universal-laptop-adapter",
      description: "Universal laptop power adapter with interchangeable tips. Compatible with most laptop brands.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "ADP-UNIV",
      retailPrice: 50000,
      bulkPrice: 45000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("universal-adapter"),
      imageAlt: "Universal Laptop Adapter",
    },
    {
      name: "Dell Type-C Laptop Cable",
      slug: "dell-typec-laptop-cable",
      description: "Dell-compatible Type-C laptop charging cable. Premium build with reliable charging performance.",
      category: ELECTRONICS,
      brand: "Dell",
      sku: "CBL-DELL-TC",
      retailPrice: 25000,
      bulkPrice: 22000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("dell-typec-cable"),
      imageAlt: "Dell Type-C Laptop Cable",
    },
    {
      name: "Dell Big Pin Laptop Cable",
      slug: "dell-big-pin-cable",
      description: "Dell laptop charging cable with big pin connector. Compatible with older Dell laptop models.",
      category: ELECTRONICS,
      brand: "Dell",
      sku: "CBL-DELL-BP",
      retailPrice: 15000,
      bulkPrice: 13000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("dell-bigpin-cable"),
      imageAlt: "Dell Big Pin Laptop Cable",
    },
    {
      name: "Lenovo Laptop Charging Cable",
      slug: "lenovo-laptop-charging-cable",
      description: "Lenovo laptop charging cable with slim tip connector. Compatible with ThinkPad and IdeaPad series.",
      category: ELECTRONICS,
      brand: "Lenovo",
      sku: "CBL-LENOVO",
      retailPrice: 25000,
      bulkPrice: 22000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("lenovo-cable"),
      imageAlt: "Lenovo Laptop Charging Cable",
    },
    {
      name: "HP Blue Pin Laptop Cable",
      slug: "hp-blue-pin-cable",
      description: "HP laptop charging cable with blue pin connector. Compatible with HP ProBook and EliteBook series.",
      category: ELECTRONICS,
      brand: "HP",
      sku: "CBL-HP-BP",
      retailPrice: 65000,
      bulkPrice: 58000,
      bulkMinQty: 5,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("hp-bluepin-cable"),
      imageAlt: "HP Blue Pin Laptop Cable",
    },
    {
      name: "Surface Laptop Charging Cable",
      slug: "surface-laptop-charging-cable",
      description: "Microsoft Surface laptop charging cable with Surface Connect tip. Genuine replacement part.",
      category: ELECTRONICS,
      brand: "Microsoft",
      sku: "CBL-SURFACE",
      retailPrice: 30000,
      bulkPrice: 27000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("surface-cable"),
      imageAlt: "Surface Laptop Charging Cable",
    },
    {
      name: "DLNA Office Phone",
      slug: "dlna-office-phone",
      description: "DLNA-compatible office phone for business communications. Features call management and network integration.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "DLNA-PHONE",
      retailPrice: 45000,
      bulkPrice: 40000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("dlna-phone"),
      imageAlt: "DLNA Office Phone",
    },
    {
      name: "Power Cable EU Standard 1M",
      slug: "power-cable-eu-1m",
      description: "Standard EU power cable, 1 meter length. Compatible with most computers, monitors, and appliances.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "CBL-PWR-EU",
      retailPrice: 2000,
      bulkPrice: 1500,
      bulkMinQty: 100,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("power-cable-eu"),
      imageAlt: "Power Cable EU Standard 1M",
    },

    // ─── LAPTOP BATTERIES ──────────────────────────────────────
    {
      name: "MacBook Pro 2015 Battery",
      slug: "macbook-pro-2015-battery",
      description: "Replacement battery for MacBook Pro 2015 model. High capacity with original specifications.",
      category: ELECTRONICS,
      brand: "Apple",
      sku: "BAT-MBP-2015",
      retailPrice: 120000,
      bulkPrice: 108000,
      bulkMinQty: 5,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("mbp-2015-battery"),
      imageAlt: "MacBook Pro 2015 Battery",
    },
    {
      name: "MacBook Pro 2016-2017 Battery",
      slug: "macbook-pro-2016-2017-battery",
      description: "Replacement battery for MacBook Pro 2016 and 2017 models. High-quality cells with reliable performance.",
      category: ELECTRONICS,
      brand: "Apple",
      sku: "BAT-MBP-1617",
      retailPrice: 80000,
      bulkPrice: 72000,
      bulkMinQty: 5,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("mbp-1617-battery"),
      imageAlt: "MacBook Pro 2016-2017 Battery",
    },
    {
      name: "MacBook Pro 2012 Battery",
      slug: "macbook-pro-2012-battery",
      description: "Replacement battery for MacBook Pro 2012 model. Durable and long-lasting performance.",
      category: ELECTRONICS,
      brand: "Apple",
      sku: "BAT-MBP-2012",
      retailPrice: 80000,
      bulkPrice: 72000,
      bulkMinQty: 5,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("mbp-2012-battery"),
      imageAlt: "MacBook Pro 2012 Battery",
    },
    {
      name: "HP EliteBook 830 G6 Battery",
      slug: "hp-elitebook-830-g6-battery",
      description: "Replacement battery for HP EliteBook 830 G6. Genuine quality cells for reliable performance.",
      category: ELECTRONICS,
      brand: "HP",
      sku: "BAT-HP-830G6",
      retailPrice: 35000,
      bulkPrice: 30000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("hp-830g6-battery"),
      imageAlt: "HP EliteBook 830 G6 Battery",
    },
    {
      name: "HP EliteBook 1040 G6 Battery",
      slug: "hp-elitebook-1040-g6-battery",
      description: "Replacement battery for HP EliteBook 1040 G6. High-capacity with long battery life.",
      category: ELECTRONICS,
      brand: "HP",
      sku: "BAT-HP-1040G6",
      retailPrice: 80000,
      bulkPrice: 72000,
      bulkMinQty: 5,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("hp-1040g6-battery"),
      imageAlt: "HP EliteBook 1040 G6 Battery",
    },
    {
      name: "HP EliteBook 840 G5 Battery",
      slug: "hp-elitebook-840-g5-battery",
      description: "Replacement battery for HP EliteBook 840 G5. Premium quality with original specifications.",
      category: ELECTRONICS,
      brand: "HP",
      sku: "BAT-HP-840G5",
      retailPrice: 45000,
      bulkPrice: 40000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("hp-840g5-battery"),
      imageAlt: "HP EliteBook 840 G5 Battery",
    },
    {
      name: "Lenovo ThinkPad T440 Battery",
      slug: "lenovo-thinkpad-t440-battery",
      description: "Replacement battery for Lenovo ThinkPad T440. High-quality cells for extended usage.",
      category: ELECTRONICS,
      brand: "Lenovo",
      sku: "BAT-LEN-T440",
      retailPrice: 40000,
      bulkPrice: 36000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("lenovo-t440-battery"),
      imageAlt: "Lenovo ThinkPad T440 Battery",
    },
    {
      name: "HP ProBook 640 G5 Battery",
      slug: "hp-probook-640-g5-battery",
      description: "Replacement battery for HP ProBook 640 G5. Durable and reliable power source.",
      category: ELECTRONICS,
      brand: "HP",
      sku: "BAT-HP-640G5",
      retailPrice: 45000,
      bulkPrice: 40000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("hp-640g5-battery"),
      imageAlt: "HP ProBook 640 G5 Battery",
    },
    {
      name: "HP EliteBook 820 G2 Battery",
      slug: "hp-elitebook-820-g2-battery",
      description: "Replacement battery for HP EliteBook 820 G2. Reliable performance for daily use.",
      category: ELECTRONICS,
      brand: "HP",
      sku: "BAT-HP-820G2",
      retailPrice: 35000,
      bulkPrice: 30000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("hp-820g2-battery"),
      imageAlt: "HP EliteBook 820 G2 Battery",
    },
    {
      name: "HP EliteBook 820 G3 Battery",
      slug: "hp-elitebook-820-g3-battery",
      description: "Replacement battery for HP EliteBook 820 G3. Premium quality with original specifications.",
      category: ELECTRONICS,
      brand: "HP",
      sku: "BAT-HP-820G3",
      retailPrice: 40000,
      bulkPrice: 36000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("hp-820g3-battery"),
      imageAlt: "HP EliteBook 820 G3 Battery",
    },
    {
      name: "Lenovo ThinkPad X260 Battery",
      slug: "lenovo-thinkpad-x260-battery",
      description: "Replacement battery for Lenovo ThinkPad X260. Extended capacity for all-day productivity.",
      category: ELECTRONICS,
      brand: "Lenovo",
      sku: "BAT-LEN-X260",
      retailPrice: 40000,
      bulkPrice: 36000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("lenovo-x260-battery"),
      imageAlt: "Lenovo ThinkPad X260 Battery",
    },
    {
      name: "HP EliteBook 840 G3 Battery",
      slug: "hp-elitebook-840-g3-battery",
      description: "Replacement battery for HP EliteBook 840 G3. High-capacity with reliable performance.",
      category: ELECTRONICS,
      brand: "HP",
      sku: "BAT-HP-840G3",
      retailPrice: 35000,
      bulkPrice: 30000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("hp-840g3-battery"),
      imageAlt: "HP EliteBook 840 G3 Battery",
    },
    {
      name: "HP ProBook 450 G5 Battery",
      slug: "hp-probook-450-g5-battery",
      description: "Replacement battery for HP ProBook 450 G5. Reliable power for your everyday computing needs.",
      category: ELECTRONICS,
      brand: "HP",
      sku: "BAT-HP-450G5",
      retailPrice: 35000,
      bulkPrice: 30000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("hp-450g5-battery"),
      imageAlt: "HP ProBook 450 G5 Battery",
    },
    {
      name: "HP EliteBook 1030 G2 Battery",
      slug: "hp-elitebook-1030-g2-battery",
      description: "Replacement battery for HP EliteBook 1030 G2. Slim design with premium battery cells.",
      category: ELECTRONICS,
      brand: "HP",
      sku: "BAT-HP-1030G2",
      retailPrice: 50000,
      bulkPrice: 45000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("hp-1030g2-battery"),
      imageAlt: "HP EliteBook 1030 G2 Battery",
    },
    {
      name: "HP EliteBook 1030 G3 Battery",
      slug: "hp-elitebook-1030-g3-battery",
      description: "Replacement battery for HP EliteBook 1030 G3. Latest generation with improved battery technology.",
      category: ELECTRONICS,
      brand: "HP",
      sku: "BAT-HP-1030G3",
      retailPrice: 60000,
      bulkPrice: 54000,
      bulkMinQty: 5,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("hp-1030g3-battery"),
      imageAlt: "HP EliteBook 1030 G3 Battery",
    },
    {
      name: "HP ProBook 640 G2 Battery",
      slug: "hp-probook-640-g2-battery",
      description: "Replacement battery for HP ProBook 640 G2. Durable and long-lasting for daily workloads.",
      category: ELECTRONICS,
      brand: "HP",
      sku: "BAT-HP-640G2",
      retailPrice: 40000,
      bulkPrice: 36000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("hp-640g2-battery"),
      imageAlt: "HP ProBook 640 G2 Battery",
    },
    {
      name: "HP EliteBook 850 G3 Battery",
      slug: "hp-elitebook-850-g3-battery",
      description: "Replacement battery for HP EliteBook 850 G3. High-performance battery for demanding users.",
      category: ELECTRONICS,
      brand: "HP",
      sku: "BAT-HP-850G3",
      retailPrice: 35000,
      bulkPrice: 30000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("hp-850g3-battery"),
      imageAlt: "HP EliteBook 850 G3 Battery",
    },
    {
      name: "HP EliteBook 840 G2 Battery",
      slug: "hp-elitebook-840-g2-battery",
      description: "Replacement battery for HP EliteBook 840 G2. Reliable power source for everyday business use.",
      category: ELECTRONICS,
      brand: "HP",
      sku: "BAT-HP-840G2",
      retailPrice: 35000,
      bulkPrice: 30000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("hp-840g2-battery"),
      imageAlt: "HP EliteBook 840 G2 Battery",
    },

    // ─── CAR TOOLS ─────────────────────────────────────────────
    {
      name: "Portable Power Station EG008PB 220V",
      slug: "portable-power-station-eg008pb",
      description: "Portable power station with AC 220V 50Hz output. Ideal for camping, emergencies, and outdoor power needs.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "PPS-EG008",
      retailPrice: 180000,
      bulkPrice: 162000,
      bulkMinQty: 5,
      stockStatus: "IN_STOCK",
      featured: true,
      image: img("power-station-eg008"),
      imageAlt: "Portable Power Station EG008PB",
    },
    {
      name: "Car Wash Machine",
      slug: "car-wash-machine",
      description: "High-pressure car wash machine for effective cleaning. Portable with multiple nozzle attachments.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "CWM-BASIC",
      retailPrice: 75000,
      bulkPrice: 68000,
      bulkMinQty: 5,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("car-wash-basic"),
      imageAlt: "Car Wash Machine",
    },
    {
      name: "High Power Car Wash Machine",
      slug: "high-power-car-wash-machine",
      description: "Professional high-power car wash machine with superior pressure and flow rate. Ideal for auto detailing.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "CWM-HP",
      retailPrice: 120000,
      bulkPrice: 108000,
      bulkMinQty: 5,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("car-wash-hp"),
      imageAlt: "High Power Car Wash Machine",
    },
    {
      name: "Car Repair Tool Kit",
      slug: "car-repair-tool-kit",
      description: "Comprehensive car repair tool kit with essential tools for automotive maintenance and repairs.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "CRTK-PRO",
      retailPrice: 250000,
      bulkPrice: 225000,
      bulkMinQty: 3,
      stockStatus: "IN_STOCK",
      featured: true,
      image: img("car-tool-kit"),
      imageAlt: "Car Repair Tool Kit",
    },
    {
      name: "Large Portable Power Station",
      slug: "large-portable-power-station",
      description: "High-capacity portable power station for heavy-duty power needs. Ideal for construction sites and outdoor events.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "PPS-LARGE",
      retailPrice: 350000,
      bulkPrice: 320000,
      bulkMinQty: 3,
      stockStatus: "IN_STOCK",
      featured: true,
      image: img("power-station-large"),
      imageAlt: "Large Portable Power Station",
    },
    {
      name: "CarPlay Rearview Mirror Dash Cam",
      slug: "carplay-rearview-mirror-dash-cam",
      description: "Smart rearview mirror dash camera with Apple CarPlay support. Front and rear recording with GPS.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "DC-CARPLAY",
      retailPrice: 200000,
      bulkPrice: 180000,
      bulkMinQty: 5,
      stockStatus: "IN_STOCK",
      featured: true,
      image: img("carplay-dashcam"),
      imageAlt: "CarPlay Rearview Mirror Dash Cam",
    },
    {
      name: "10\" Touch Screen Night Vision Dash Cam",
      slug: "10-inch-touch-dash-cam",
      description: "Large 10-inch touch screen dash camera with starlight night vision. Advanced driver assistance features.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "DC-10INCH",
      retailPrice: 100000,
      bulkPrice: 90000,
      bulkMinQty: 5,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("dashcam-10inch"),
      imageAlt: "10\" Touch Screen Dash Cam",
    },
    {
      name: "Professional Tool Box",
      slug: "professional-tool-box",
      description: "Heavy-duty professional tool box with organized storage. Ideal for mechanics and technicians.",
      category: ELECTRONICS,
      brand: "Generic",
      sku: "TB-PRO",
      retailPrice: 400000,
      bulkPrice: 360000,
      bulkMinQty: 2,
      stockStatus: "IN_STOCK",
      featured: true,
      image: img("tool-box-pro"),
      imageAlt: "Professional Tool Box",
    },

    // ─── AROMA DIFFUSERS (IMITAKO) ─────────────────────────────
    {
      name: "Fireplace Aromatherapy Humidifier",
      slug: "fireplace-aromatherapy-humidifier",
      description: "Fireplace-style aromatherapy humidifier with warm LED lighting. Creates a cozy atmosphere while diffusing essential oils.",
      category: ELECTRONICS,
      brand: "IMITAKO",
      sku: "ARD-FP",
      retailPrice: 50000,
      bulkPrice: 45000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("aroma-fireplace"),
      imageAlt: "Fireplace Aromatherapy Humidifier",
    },
    {
      name: "Flame Fireplace Aroma Diffuser",
      slug: "flame-fireplace-aroma-diffuser",
      description: "Flame-effect aroma diffuser with realistic fireplace visuals. Combines humidifier and essential oil diffuser.",
      category: ELECTRONICS,
      brand: "IMITAKO",
      sku: "ARD-FLAME",
      retailPrice: 50000,
      bulkPrice: 45000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("aroma-flame"),
      imageAlt: "Flame Fireplace Aroma Diffuser",
    },
    {
      name: "RaiDrop Aroma Diffuser",
      slug: "raidrop-aroma-diffuser",
      description: "RaiDrop ultrasonic aroma diffuser with rain-like water droplet effect. Quiet operation with auto shut-off.",
      category: ELECTRONICS,
      brand: "IMITAKO",
      sku: "ARD-RAIDROP",
      retailPrice: 50000,
      bulkPrice: 45000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("aroma-raidrop"),
      imageAlt: "RaiDrop Aroma Diffuser",
    },
    {
      name: "V88 Rotating Water Drop Aroma Diffuser",
      slug: "v88-rotating-aroma-diffuser",
      description: "V88 rotating water drop aroma diffuser with mesmerizing visual effects. Large capacity tank for extended use.",
      category: ELECTRONICS,
      brand: "IMITAKO",
      sku: "ARD-V88",
      retailPrice: 50000,
      bulkPrice: 45000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("aroma-v88"),
      imageAlt: "V88 Rotating Water Drop Aroma Diffuser",
    },
    {
      name: "Deep Sea Elf Aroma Diffuser",
      slug: "deep-sea-elf-aroma-diffuser",
      description: "Deep Sea Elf themed aroma diffuser with underwater lighting effects. Fun and decorative for any room.",
      category: ELECTRONICS,
      brand: "IMITAKO",
      sku: "ARD-DSEA",
      retailPrice: 50000,
      bulkPrice: 45000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("aroma-deep-sea"),
      imageAlt: "Deep Sea Elf Aroma Diffuser",
    },
    {
      name: "V89 Rotating Water Drop Aroma Diffuser",
      slug: "v89-rotating-aroma-diffuser",
      description: "V89 rotating water drop aroma diffuser with upgraded design. Silent operation with ambient LED lighting.",
      category: ELECTRONICS,
      brand: "IMITAKO",
      sku: "ARD-V89",
      retailPrice: 50000,
      bulkPrice: 45000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("aroma-v89"),
      imageAlt: "V89 Rotating Water Drop Aroma Diffuser",
    },
    {
      name: "FirePlace Lantern Aroma Diffuser",
      slug: "fireplace-lantern-aroma-diffuser",
      description: "Lantern-style fireplace aroma diffuser with warm glow. Portable and decorative for indoor and outdoor use.",
      category: ELECTRONICS,
      brand: "IMITAKO",
      sku: "ARD-LANTERN",
      retailPrice: 55000,
      bulkPrice: 50000,
      bulkMinQty: 10,
      stockStatus: "IN_STOCK",
      featured: true,
      image: img("aroma-lantern"),
      imageAlt: "FirePlace Lantern Aroma Diffuser",
    },
    {
      name: "Jasmine Essential Oil Aromatologia",
      slug: "jasmine-essential-oil",
      description: "Pure jasmine essential oil by Aromatologia. Premium quality for aromatherapy and relaxation.",
      category: STATIONERY,
      brand: "Aromatologia",
      sku: "EO-JASMINE",
      retailPrice: 5000,
      bulkPrice: 4000,
      bulkMinQty: 50,
      stockStatus: "IN_STOCK",
      featured: false,
      image: img("jasmine-oil"),
      imageAlt: "Jasmine Essential Oil",
    },
  ];

  console.log(`Seeding ${products.length} products...`);

  for (const product of products) {
    const { image, imageAlt, ...data } = product;
    await prisma.product.upsert({
      where: { sku: data.sku },
      update: data as never,
      create: {
        ...(data as never),
        images: {
          create: { url: image, alt: imageAlt, isPrimary: true, order: 0 },
        },
      },
    });
  }

  console.log(`✓ ${products.length} products seeded`);
  console.log("ELOHOME database seeding complete!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
